[default]
    LOG_TO_CONSOLE = true
    LOG_TO_FILE = false
    ENABLE_DOCS = true

    SLACK_USER_TOKEN = "xoxp-not-a-valid-token-1234567890"
    SLACK_BOT_TOKEN = "xoxb-not-a-valid-token-1234567890"
